default: &default
  adapter: postgres

development:
  <<: *default
  database: linkoumet_development

test:
  <<: *default
  database: linkoumet_test

production:
  <<: *default
  database: linkoumet_production
