module SolidSecret
  SESSION_SECRET = ENV['SESSION_SECRET'] || ''
  FB_APP_ID = ENV['FB_APP_ID'] || ''
  FB_APP_SECRET = ENV['FB_APP_SECRET'] || ''
  TWITTER_CONSUMER_KEY = ENV['TWITTER_CONSUMER_KEY'] || ''
  TWITTER_CONSUMER_SECRET = ENV['TWITTER_CONSUMER_SECRET'] || ''
end
